apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-web
  template:
    metadata:
      labels:
        app: python-web
    spec:
      containers:
      - name: python-web
        image: python-minikube-demo
        imagePullPolicy: Never  # Important for local images
        ports:
        - containerPort: 8080